package com.company.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModeloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloAllPropertiesEquals(Modelo expected, Modelo actual) {
        assertModeloAutoGeneratedPropertiesEquals(expected, actual);
        assertModeloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloAllUpdatablePropertiesEquals(Modelo expected, Modelo actual) {
        assertModeloUpdatableFieldsEquals(expected, actual);
        assertModeloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloAutoGeneratedPropertiesEquals(Modelo expected, Modelo actual) {
        assertThat(expected)
            .as("Verify Modelo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloUpdatableFieldsEquals(Modelo expected, Modelo actual) {
        assertThat(expected)
            .as("Verify Modelo relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloUpdatableRelationshipsEquals(Modelo expected, Modelo actual) {
        assertThat(expected)
            .as("Verify Modelo relationships")
            .satisfies(e -> assertThat(e.getMarca()).as("check marca").isEqualTo(actual.getMarca()));
    }
}
